### ISSUE TITLE
Cannot find module './DtsCreator'

### ISSUE THREAD

**Issue by xuyangbill** [Quramy/typed-css-modules#70]
works well with 0.4.2,fail with 0.5.0

check the logs below
$ npm install -g typed-css-modules
...
$ ls /opt/node/lib/node_modules/typed-css-modules/lib/
DtsContent.d.ts
DtsContent.js
DtsCreator.d.ts
FileSystemLoader.d.ts
cli.d.ts
cli.js
dtsCreator.js
fileSystemLoader.js
index.d.ts
index.js
tokenValidator.js
$ export DONT_INSTALL_HOOKS=true
$ tcm --pattern ./packages/**/*.module.scss -c
module.js:550
    throw err;
    ^

Error: Cannot find module './DtsCreator'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/node/lib/node_modules/typed-css-modules/lib/cli.js:27:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by antross** [comment]
I ran into this too, but only when running on Linux. 

It looks like a case-sensitivity issue with the filename that happened due to the rename of `dtsCreator.ts` to `DtsCreator.ts` in https://github.com/Quramy/typed-css-modules/commit/4c91ead0aa36fafa2940484640c9d3167482b2e0.

I'd guess the build was run on a case-insensitive OS with `dtsCreator.js` already existing so the output file didn't get renamed. Probably can be fixed by deleting `dtsCreator.js` and rebuilding+republishing.

**Comment by Quramy** [comment]
Ok, I'll rename them using not camel cased names but kebab cased names.

**Comment by Quramy** [comment]
@xuyangbill I've fixed it as #71 and published it as v0.5.1. Pls check it out 🙏

**Comment by xuyangbill** [comment]
0.5.1 works,thanks

**Comment by gdelmas** [comment]
hey @Quramy,

i had a look at the released npm packages and as @antross is suggesting the problem is not the name of the files, but that there were old files from previous builds in the lib directory. the solution here would be to change the build script, so that the build artifacts are always clean and reproducible. additionally setting up a .npmignore, so that things like coverage reports and other unnecessary files are not part of the package.

i'd be happy to make an MR for this. in regards to the filenames there does not need to be any change. the current fix adds some indirection, as files now have a different name than their containing classes. i'd be happy to make this more consistent as well. as i assume the file naming was not the root problem.

what do you think?
